// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMapping } from "./ColumnMapping";

export type ColumnMappings = Array<ColumnMapping>;