// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ColumnMap { tensor_id: string, node_name: string, input_tensor_name: string, }