// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";

export interface DatasetInfo { id: string, name: string, num_rows: number, schema: Schema, }