// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schema } from "./Schema";
import type { TensorInfo } from "./TensorInfo";

export interface DatasetInfo { id: string, display_name: string, num_rows: number, schema: Schema, registered_tensors: Array<TensorInfo>, }