// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ElementType = "U8" | "I8" | "U16" | "I16" | "U32" | "I32" | "F32" | "U64" | "I64" | "F64" | "Utf8";