// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataType } from "./DataType";

export interface Field { name: string, data_type: DataType, nullable: boolean, metadata: Record<string, string> | null, }