// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export interface Node { type: NodeKind, identifier: string, args: Record<string, string>, }