// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeInput } from "./NodeInput";
import type { NodeKind } from "./NodeKind";

export interface Node { type: NodeKind, identifier: string, inputs: Record<string, NodeInput>, args: Record<string, string>, }