// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";

export interface Schema { fields: Array<Field>, metadata: Record<string, string> | null, }