// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export 
interface SerializableError<E> {
    /** A human-readable message explaining the top-most error. */
    message: string,
    /** A list of errors that resulted in this error */
    causes: string[],
    /** A verbose stacktrace of the error. */
    verbose: string,
    /** Some optional, domain-specific data that describes this error. */
    state?: E,
}