// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementType } from "./ElementType";

export interface TensorInfo { id: string, display_name: string, dimensions: Array<number>, element_type: ElementType, }