[package]
name = "tauri-plugin-defrag-duckdb"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.57"
exclude = ["/examples"]

[dependencies]
duckdb = "0.3.4"
tauri = { version = "1.0.0-rc.9" }
